name: tuple_glados
description: "Provides Glados generators for types from the tuple package."
version: 1.0.0
repository: https://github.com/MarcelGarus/glados

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  tuple: ^2.0.0
  flutter_glados: ^1.1.6
